### ISSUE TITLE
Runtime error with g++10

### ISSUE THREAD

**Issue by sb-qt** [maekitalo/tntdb#14]
In file  tntdb/src/librarymanager.cpp I found out on my Debian 11 with g++10, that the following is not working anymore:

-----
        std::string d = DRIVERDIR + cxxtools::Directory::sep() + libraryPrefix + driverName;
        log_debug("loading library \"" << d << '"');
        lib = cxxtools::Library(d);
-------
To get it work, I have changed the code to:
-------
        std::string d(DRIVERDIR);
        d += cxxtools::Directory::sep() + libraryPrefix + driverName;
        log_debug("loading library \"" << d << '"');
        lib = cxxtools::Library(d);
-------

Best regards,
Sven

**Comment by maekitalo** [comment]
Fixed. Thank you.
